additional cleanup

diff --git a/sle15/official-packages/Dockerfile b/sle15/official-packages/Dockerfile
--- a/sle15/official-packages/Dockerfile
+++ b/sle15/official-packages/Dockerfile
@@ -84,6 +84,15 @@ RUN cp -r /lib/firmware /opt/lib
 
 RUN zypper removerepo cuda-sles15
 
+# cleanup logs and temporary files
+RUN set -euo pipefail; zypper -n --installroot /target clean -a; \
+    rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
+    rm -rf {/target,}/run/*; \
+    rm -f {/target,}/etc/{shadow-,group-,passwd-,.pwd.lock}; \
+    rm -f {/target,}/usr/lib/sysimage/rpm/.rpm.lock; \
+    rm -f {/target,}/var/cache/ldconfig/aux-cache; \
+    command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
+
 WORKDIR /drivers
 
 #ARG PUBLIC_KEY=empty
