disable additional firmware path

diff --git a/sle15/official-packages/nvidia-driver b/sle15/official-packages/nvidia-driver
--- a/sle15/official-packages/nvidia-driver
+++ b/sle15/official-packages/nvidia-driver
@@ -268,15 +268,15 @@ _load_driver() {
         fi
     done
 
-    if [[ "$set_fw_path" == "true" ]]; then
-        echo "Configuring the following firmware search path in '$fw_path_config_file': $nv_fw_search_path"
-        if [[ ! -z $(grep '[^[:space:]]' $fw_path_config_file) ]]; then
-            echo "WARNING: A search path is already configured in $fw_path_config_file"
-            echo "         Retaining the current configuration"
-        else
-            echo -n "$nv_fw_search_path" > $fw_path_config_file || echo "WARNING: Failed to configure the firmware search path"
-        fi
-    fi
+#    if [[ "$set_fw_path" == "true" ]]; then
+#        echo "Configuring the following firmware search path in '$fw_path_config_file': $nv_fw_search_path"
+#        if [[ ! -z $(grep '[^[:space:]]' $fw_path_config_file) ]]; then
+#            echo "WARNING: A search path is already configured in $fw_path_config_file"
+#            echo "         Retaining the current configuration"
+#        else
+#            echo -n "$nv_fw_search_path" > $fw_path_config_file || echo "WARNING: Failed to configure the firmware search path"
+#        fi
+#    fi
 
     echo "Loading ipmi and i2c_core kernel modules..."
     modprobe -d /opt -a i2c_core ipmi_msghandler ipmi_devintf
@@ -451,8 +451,8 @@ _mount_rootfs() {
     echo "Mounting NVIDIA driver rootfs..."
     mount --make-runbindable /sys
     mount --make-private /sys
-    mkdir -p ${RUN_DIR}/driver
-    mount --rbind / ${RUN_DIR}/driver
+#    mkdir -p ${RUN_DIR}/driver
+#    mount --rbind / ${RUN_DIR}/driver
 
     echo "Check SELinux status"
     if [ -e /sys/fs/selinux ]; then
